### Import libraries
```{r}
library(pacman)
pacman::p_load(tidyverse, ggplot2, emmeans, sandwich, lmtest, lmerTest, performance, see)
options(scipen = 999)
```

### Combine all data saving information on genres and seed
```{r}
read_bias_data <- function(genre, seed) {
  file <- glue::glue("data/associational_gender_bias/{genre}_gender_bias_seed_{seed}.csv")
  read_csv(file)
}

genres <- c("romance", "sci-fi", "literary fiction")
seeds  <- c("1", "7", "13", "42", "99", "123", "256", "512", "777", "999")

all_data <- expand_grid(genre = genres, seed = seeds) %>%
  mutate(data = map2(genre, seed, read_bias_data))

bias_data_all <- all_data %>%
  unnest(data)

```

```{r}
bias_data_all %>%
  count(genre, seed)
```

```{r}
# create a dataset for each unique seed
groups <- bias_data_all %>%
  group_by(seed) %>%
  group_split()

keys <- bias_data_all %>%
  distinct(seed) %>%
  pull(seed)

names(groups) <- paste0("seed_", keys)
```

### Modeling (including random intercept for seed to account for variability across seeds)
```{r}
# Random-intercept model for seed
model <- lmerTest::lmer(
  gender_bias ~  dimension * genre + (1 | seed),
  data = bias_data_all
)

summary(model) # random effects are 0
```

```{r}
performance::check_model(model)
```

### Fit a simpler model

```{r}
# read romance_gender_bias_averaged_seeds.csv
romance_averaged = read_csv("data/associational_gender_bias/romance_gender_bias_averaged_seeds.csv")
lit_fic_averaged = read_csv("data/associational_gender_bias/literary_fiction_gender_bias_averaged_seeds.csv")
sci_fi_averaged = read_csv("data/associational_gender_bias/sci_fi_gender_bias_averaged_seeds.csv")
```


```{r}
# Combine into one dataset
bias_data_averaged <- bind_rows(
  romance_averaged %>% mutate(genre = "romance"),
  lit_fic_averaged %>% mutate(genre = "literary_fiction"),
  sci_fi_averaged %>% mutate(genre = "sci-fi")
)
```


```{r}
model_lm <- lm(gender_bias ~ dimension * genre, data = bias_data_averaged)
summary(model_lm)
```

```{r}
emm <- emmeans(model_lm, ~ dimension * genre)
summary(emm, infer = c(TRUE, TRUE), adjust = "fdr")
```


```{r}
performance::check_model(model_lm)
```


